# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

include(CMakeFindDependencyMacro)

set(
    CMAKE_PREFIX_PATH
    "${CMAKE_PREFIX_PATH}" "${CMAKE_CURRENT_LIST_DIR}/../external"
    CACHE STRING "" FORCE
)

find_dependency(tensorwrapper)

list(LENGTH chemist_FIND_COMPONENTS chemist_FIND_COMPONENTS_len)
if(chemist_FIND_COMPONENTS_len LESS_EQUAL 0)
    list(APPEND chemist_FIND_COMPONENTS chemist)
endif()

foreach(component ${chemist_FIND_COMPONENTS})
    include(${CMAKE_CURRENT_LIST_DIR}/${component}-target.cmake)
endforeach()

