// Copyright (c) 2017-2021, University of Tennessee. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
// This program is free software: you can redistribute it and/or modify it under
// the terms of the BSD 3-Clause license. See the accompanying LICENSE file.

#ifndef BLAS_DEFINES_H
#define BLAS_DEFINES_H

// auto-generated by: 
// /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake 3.26.4
// host: visitor-wireless1-147-155-221-138.ameslab.gov
//
// Definitions for:
// CXX   = 
//         /opt/homebrew/Cellar/gcc@11/11.4.0/bin/g++-11
// LIBS  = 
//         /opt/homebrew/lib/libscalapack.dylib;MPI::MPI_C;-L/usr/local/opt/openblas/lib;-lblas;-llapack

#define BLAS_FORTRAN_ADD_
#define BLAS_COMPLEX_RETURN_ARGUMENT
#define BLAS_HAVE_F2C


#endif        //  #ifndef BLAS_DEFINES_H
