# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

if(TARGET nwx::tensorwrapper)
    return()
endif()

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

# Create imported target nwx::tensorwrapper
add_library(nwx::tensorwrapper SHARED IMPORTED)

set_target_properties(nwx::tensorwrapper PROPERTIES
    INTERFACE_COMPILE_FEATURES "cxx_std_17"
    INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_PREFIX_DIR}/include"
    INTERFACE_LINK_LIBRARIES "nwx::utilities;nwx::parallelzone;tiledarray"
)

set(_CMAIZE_IMPORT_LOCATION "${PACKAGE_PREFIX_DIR}/lib/tensorwrapper/libtensorwrapper.1.0.0.dylib")

# Import target "nwx::tensorwrapper" for configuration "???"
set_property(TARGET nwx::tensorwrapper APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(nwx::tensorwrapper PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_CMAIZE_IMPORT_LOCATION}"
    IMPORTED_SONAME_RELEASE "libtensorwrapper.1.dylib"
)

# Unset variables used
set(PACKAGE_PREFIX_DIR)
set(_CMAIZE_IMPORT_LOCATION)
