# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

include(CMakeFindDependencyMacro)

set(
    CMAKE_PREFIX_PATH
    "${CMAKE_PREFIX_PATH}" "${CMAKE_CURRENT_LIST_DIR}/../external"
    CACHE STRING "" FORCE
)

find_dependency(MADNESS COMPONENTS MADworld)
find_dependency(spdlog)
find_dependency(cereal)

list(LENGTH parallelzone_FIND_COMPONENTS parallelzone_FIND_COMPONENTS_len)
if(parallelzone_FIND_COMPONENTS_len LESS_EQUAL 0)
    list(APPEND parallelzone_FIND_COMPONENTS parallelzone)
endif()

foreach(component ${parallelzone_FIND_COMPONENTS})
    include(${CMAKE_CURRENT_LIST_DIR}/${component}-target.cmake)
endforeach()

