# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

if(TARGET nwx::pluginplay)
    return()
endif()

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

# Create imported target nwx::pluginplay
add_library(nwx::pluginplay SHARED IMPORTED)

set_target_properties(nwx::pluginplay PROPERTIES
    INTERFACE_COMPILE_FEATURES "cxx_std_17"
    INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_PREFIX_DIR}/include"
    INTERFACE_LINK_LIBRARIES "nwx::utilities;nwx::parallelzone;libfort::fort"
)

set(_CMAIZE_IMPORT_LOCATION "${PACKAGE_PREFIX_DIR}/lib/pluginplay/libpluginplay.1.0.0.dylib")

# Import target "nwx::pluginplay" for configuration "???"
set_property(TARGET nwx::pluginplay APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(nwx::pluginplay PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_CMAIZE_IMPORT_LOCATION}"
    IMPORTED_SONAME_RELEASE "libpluginplay.1.dylib"
)

# Unset variables used
set(PACKAGE_PREFIX_DIR)
set(_CMAIZE_IMPORT_LOCATION)
