# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

include(CMakeFindDependencyMacro)

set(
    CMAKE_PREFIX_PATH
    "${CMAKE_PREFIX_PATH}" "${CMAKE_CURRENT_LIST_DIR}/../external"
    CACHE STRING "" FORCE
)

find_dependency(utilities)
find_dependency(parallelzone)
find_dependency(libfort COMPONENTS fort)

list(LENGTH pluginplay_FIND_COMPONENTS pluginplay_FIND_COMPONENTS_len)
if(pluginplay_FIND_COMPONENTS_len LESS_EQUAL 0)
    list(APPEND pluginplay_FIND_COMPONENTS pluginplay)
endif()

foreach(component ${pluginplay_FIND_COMPONENTS})
    include(${CMAKE_CURRENT_LIST_DIR}/${component}-target.cmake)
endforeach()

