# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

if(TARGET nwx::simde)
    return()
endif()

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)

# Create imported target nwx::simde
add_library(nwx::simde SHARED IMPORTED)

set_target_properties(nwx::simde PROPERTIES
    INTERFACE_COMPILE_FEATURES "cxx_std_17"
    INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_PREFIX_DIR}/include"
    INTERFACE_LINK_LIBRARIES "nwx::chemist;nwx::pluginplay"
)

set(_CMAIZE_IMPORT_LOCATION "${PACKAGE_PREFIX_DIR}/lib/simde/libsimde.1.0.0.dylib")

# Import target "nwx::simde" for configuration "???"
set_property(TARGET nwx::simde APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(nwx::simde PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_CMAIZE_IMPORT_LOCATION}"
    IMPORTED_SONAME_RELEASE "libsimde.1.dylib"
)

# Unset variables used
set(PACKAGE_PREFIX_DIR)
set(_CMAIZE_IMPORT_LOCATION)
