# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

include(CMakeFindDependencyMacro)

set(
    CMAKE_PREFIX_PATH
    "${CMAKE_PREFIX_PATH}" "${CMAKE_CURRENT_LIST_DIR}/../external"
    CACHE STRING "" FORCE
)

find_dependency(chemist)
find_dependency(pluginplay)

list(LENGTH simde_FIND_COMPONENTS simde_FIND_COMPONENTS_len)
if(simde_FIND_COMPONENTS_len LESS_EQUAL 0)
    list(APPEND simde_FIND_COMPONENTS simde)
endif()

foreach(component ${simde_FIND_COMPONENTS})
    include(${CMAKE_CURRENT_LIST_DIR}/${component}-target.cmake)
endforeach()

