# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run.

include(CMakeFindDependencyMacro)


list(LENGTH utilities_FIND_COMPONENTS utilities_FIND_COMPONENTS_len)
if(utilities_FIND_COMPONENTS_len LESS_EQUAL 0)
    list(APPEND utilities_FIND_COMPONENTS utilities)
endif()

foreach(component ${utilities_FIND_COMPONENTS})
    include(${CMAKE_CURRENT_LIST_DIR}/${component}-target.cmake)
endforeach()

