#ifndef LAPACK_DEFINES_H
#define LAPACK_DEFINES_H

// auto-generated by: 
// /opt/homebrew/Cellar/cmake/3.26.4/bin/cmake 3.26.4
// host: visitor-wireless1-147-155-221-138.ameslab.gov
//
// Definitions for:
// CXX   = 
//         /opt/homebrew/Cellar/gcc@11/11.4.0/bin/g++-11
// LIBS  = 
//         /opt/homebrew/lib/libscalapack.dylib;MPI::MPI_C;-L/usr/local/opt/openblas/lib;-lblas;-llapack
//         -L/usr/local/opt/openblas/lib;-lblas;-llapack

#define LAPACK_HAVE_LAPACK
#define LAPACK_VERSION 30201


#endif /* LAPACK_DEFINES_H */
