#include "xyz_write.h"

void print_positions(std::string file_name, Atom* atoms, int num) {
    std::ofstream file(file_name);

    file << num << std::endl << "Generated by personal code" << std::endl;

    for(int i = 0; i < num; i++) { file << atoms[i].to_string(); }

    file.close();
}
