name: Build and Deploy Documentation
on:
  push:
    branches:
      - master

jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    env:
      cmake_version: 3.16.3
      arch: Linux-x86_64
    steps:
      - name: Obtain Source
        uses: actions/checkout@v2
      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2
      - name: Configure C++ documentation
        run: cmake -H. -Bbuild -DONLY_BUILD_DOCS=True -DBUILD_DOCS=True
      - name: Build C++ documentation
        run: cmake --build build --target ghostfragment_cxx_api  
      - name: Build Sphinx Documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: Add C++ documentation to Sphinx
        run: mv build/html build/docs/html/cxx_api
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CREATE_PULL_REQUEST_TOKEN }}
          publish_dir: ./build/docs/html